AWSTemplateFormatVersion: '2010-09-09'
Resources:

  PasswordManagerRDSSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: PasswordManagerRDSSecurityGroup
      GroupDescription: Security group for Password Manager RDS instance
      VpcId: <vpc id>
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: '0.0.0.0/0'

  PasswordManagerRDSInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBInstanceIdentifier: PasswordManagerRDS
      Engine: mysql
      EngineVersion: '8.0.23'
      LicenseModel: general-public-license
      MasterUsername: <username>
      MasterUserPassword: <password>
      AllocatedStorage: '20'
      DBInstanceClass: db.t2.micro
      VPCSecurityGroups:
        - !Ref PasswordManagerRDSSecurityGroup
      DBSubnetGroupName: !Ref PasswordManagerDBSubnetGroup
      MultiAZ: false
      PubliclyAccessible: true

  PasswordManagerDBSubnetGroup:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupDescription: Subnet group for Password Manager RDS instance
      SubnetIds: 
        - <subnet ids>

Outputs:
  RDSInstanceEndpoint:
    Description: RDS instance endpoint
    Value: !GetAtt PasswordManagerRDSInstance.Endpoint.Address
